exclude_from_localizations: ["assets", "CNAME"]
lang: en
languageNames:
  ru: RU
  en: EN

title_header: Personal blog of WEB developer Kovalev Konstantin
author: Konstantin Kovalev
title: Konstantin Kovalev (aka kovаlevcon)
email: kovalevcon@mail.ru
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog of WEB developer Konstantin Kovalev | Персональный блог WEB разработчика Ковалева Константина
footer_title:
  My name is Konstantin Kovalev and this is my blog.
  A blog in which I displayed detailed information about myself as a WEB developer.
  If you have any suggestions or questions, please contact me.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: kovalevcon
linkedin_username: constantine-kovalev-474859bb
telegram_username: kovalevcon

# Build settings
markdown: kramdown
theme: minima
